services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    environment:
      - PORT=8000

volumes:
  postgres_data: